'use client';

import { useEffect, useRef, useState } from 'react';
import { Maximize2, X, ZoomIn, ZoomOut, RotateCcw } from 'lucide-react';

interface DiagramBlockProps {
  /** Raw mermaid syntax string from the SSE stream */
  definition: string;
  /** Optional title shown above the diagram */
  title?: string;
}

/* ── Mermaid loader (lazy, singleton) ──────────────────────────── */
let mermaidReady: Promise<typeof import('mermaid')> | null = null;

function loadMermaid() {
  if (!mermaidReady) {
    mermaidReady = import('mermaid').then((mod) => {
      mod.default.initialize({
        startOnLoad: false,
        theme: 'dark',
        themeVariables: {
          background:       '#0D0D0F',
          primaryColor:     '#1E1E2A',
          primaryTextColor: 'rgba(255,255,255,0.82)',
          primaryBorderColor: 'rgba(255,255,255,0.10)',
          lineColor:        'rgba(255,255,255,0.25)',
          secondaryColor:   '#16161E',
          tertiaryColor:    '#1A1A24',
          edgeLabelBackground: '#0D0D0F',
          nodeTextColor:    'rgba(255,255,255,0.82)',
          clusterBkg:       '#16161E',
          titleColor:       'rgba(255,255,255,0.60)',
          fontFamily:       'ui-sans-serif, system-ui, sans-serif',
          fontSize:         '13px',
        },
        flowchart:  { curve: 'basis', useMaxWidth: true },
        sequence:   { useMaxWidth: true, wrap: true },
        gantt:      { useMaxWidth: true },
      });
      return mod;
    });
  }
  return mermaidReady;
}

/**
 * Sets the SVG content produced by mermaid.render() into a container element.
 * This is safe: mermaid.render() generates sanitized SVG from its own parser —
 * it does not pass through user HTML. The output is trusted library-generated markup.
 */
function setSVGContent(container: HTMLDivElement, svgMarkup: string) {
  // Safe: svgMarkup is generated by mermaid's internal renderer, not user input
  container.innerHTML = svgMarkup; // eslint-disable-line no-unsanitized/property
}

/* ── Diagram renderer (inline) ──────────────────────────────────── */
function MermaidSVG({
  definition,
  id,
  onSVGReady,
}: {
  definition: string;
  id: string;
  onSVGReady?: (svg: string) => void;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!ref.current) return;
    let cancelled = false;

    loadMermaid().then(async (mermaid) => {
      if (cancelled || !ref.current) return;
      try {
        const { svg } = await mermaid.default.render(id, definition);
        if (cancelled || !ref.current) return;

        setSVGContent(ref.current, svg);

        const svgEl = ref.current.querySelector('svg');
        if (svgEl) {
          svgEl.removeAttribute('height');
          svgEl.style.maxWidth = '100%';
          svgEl.style.height = 'auto';
          svgEl.style.display = 'block';
        }

        onSVGReady?.(svg);
        setError(null);
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : 'Diagram error');
        }
      }
    });

    return () => { cancelled = true; };
  }, [definition, id, onSVGReady]);

  if (error) {
    return (
      <div
        className="rounded-lg px-3 py-2 text-[12px]"
        style={{ background: 'rgba(239,68,68,0.10)', color: 'rgba(252,165,165,0.80)' }}
      >
        Could not render diagram: {error}
      </div>
    );
  }

  return <div ref={ref} className="w-full overflow-x-auto" />;
}

/* ── Fullscreen modal ───────────────────────────────────────────── */
function FullscreenModal({
  definition,
  title,
  onClose,
}: {
  definition: string;
  title?: string;
  onClose: () => void;
}) {
  const [scale, setScale] = useState(1);
  const modalId = `mermaid-fs-${Math.random().toString(36).slice(2)}`;

  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  return (
    <div
      className="fixed inset-0 z-50 flex flex-col"
      style={{ background: 'rgba(0,0,0,0.88)', backdropFilter: 'blur(8px)' }}
      onClick={onClose}
    >
      <div
        className="flex items-center justify-between px-4 py-3 flex-shrink-0"
        style={{ borderBottom: '1px solid rgba(255,255,255,0.08)' }}
        onClick={(e) => e.stopPropagation()}
      >
        <span className="text-[13px] font-medium" style={{ color: 'rgba(255,255,255,0.70)' }}>
          {title || 'Diagram'}
        </span>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setScale((s) => Math.max(0.5, s - 0.25))}
            className="p-1.5 rounded-lg transition-colors"
            style={{ color: 'rgba(255,255,255,0.50)', background: 'rgba(255,255,255,0.06)', border: 'none', cursor: 'pointer' }}
          >
            <ZoomOut size={15} strokeWidth={1.5} />
          </button>
          <span className="text-[12px] tabular-nums w-8 text-center" style={{ color: 'rgba(255,255,255,0.40)' }}>
            {Math.round(scale * 100)}%
          </span>
          <button
            onClick={() => setScale((s) => Math.min(3, s + 0.25))}
            className="p-1.5 rounded-lg transition-colors"
            style={{ color: 'rgba(255,255,255,0.50)', background: 'rgba(255,255,255,0.06)', border: 'none', cursor: 'pointer' }}
          >
            <ZoomIn size={15} strokeWidth={1.5} />
          </button>
          <button
            onClick={() => setScale(1)}
            className="p-1.5 rounded-lg transition-colors"
            style={{ color: 'rgba(255,255,255,0.50)', background: 'rgba(255,255,255,0.06)', border: 'none', cursor: 'pointer' }}
          >
            <RotateCcw size={15} strokeWidth={1.5} />
          </button>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg transition-colors ml-1"
            style={{ color: 'rgba(255,255,255,0.60)', background: 'rgba(255,255,255,0.08)', border: 'none', cursor: 'pointer' }}
          >
            <X size={16} strokeWidth={1.5} />
          </button>
        </div>
      </div>

      <div
        className="flex-1 overflow-auto p-6"
        onClick={(e) => e.stopPropagation()}
      >
        <div
          style={{
            transform: `scale(${scale})`,
            transformOrigin: 'top center',
            transition: 'transform 0.15s ease',
          }}
        >
          <MermaidSVG definition={definition} id={modalId} />
        </div>
      </div>
    </div>
  );
}

/* ── Main export: DiagramBlock ──────────────────────────────────── */
export function DiagramBlock({ definition, title }: DiagramBlockProps) {
  const [fullscreen, setFullscreen] = useState(false);
  const inlineId = useRef(`mermaid-${Math.random().toString(36).slice(2)}`).current;

  return (
    <>
      <div
        className="w-full rounded-xl overflow-hidden"
        style={{
          background: 'rgba(255,255,255,0.03)',
          border: '1px solid rgba(255,255,255,0.07)',
        }}
      >
        <div
          className="flex items-center justify-between px-3 py-2"
          style={{ borderBottom: '1px solid rgba(255,255,255,0.06)' }}
        >
          <span className="text-[11px] font-medium uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.35)' }}>
            {title || 'Diagram'}
          </span>
          <button
            onClick={() => setFullscreen(true)}
            className="flex items-center gap-1 px-2 py-1 rounded-lg text-[11px] transition-colors"
            style={{ color: 'rgba(255,255,255,0.40)', background: 'transparent', border: 'none', cursor: 'pointer' }}
            onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.06)'; e.currentTarget.style.color = 'rgba(255,255,255,0.70)'; }}
            onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.color = 'rgba(255,255,255,0.40)'; }}
          >
            <Maximize2 size={12} strokeWidth={1.5} />
            <span className="hidden sm:inline">Expand</span>
          </button>
        </div>

        <div
          className="p-3 overflow-x-auto"
          style={{ WebkitOverflowScrolling: 'touch' }}
        >
          <MermaidSVG definition={definition} id={inlineId} />
        </div>

        <div
          className="px-3 pb-2 text-[10px] sm:hidden"
          style={{ color: 'rgba(255,255,255,0.25)' }}
        >
          Tap expand for full view
        </div>
      </div>

      {fullscreen && (
        <FullscreenModal
          definition={definition}
          title={title}
          onClose={() => setFullscreen(false)}
        />
      )}
    </>
  );
}
