import type { AgentTool, AgentContext, OutputFile } from "@/lib/ai/agent/types";
import { uploadFile } from "@/lib/storage";
import { runChartInSandbox } from "../utils/run-chart";

export const generateSlidesTool: AgentTool = {
  name: "generate_slides",
  description:
    "Generate a PowerPoint (PPTX) presentation with a dark theme. Provide a title and an array of slides, each with a title, bullet points, and optional Python chart code. Charts are rendered via a sandbox and placed on the right half of the slide.",
  input_schema: {
    type: "object",
    properties: {
      title: {
        type: "string",
        description: "The presentation title (shown on the title slide).",
      },
      slides: {
        type: "array",
        description: "Array of content slides.",
        items: {
          type: "object",
          properties: {
            title: {
              type: "string",
              description: "Slide heading.",
            },
            bullets: {
              type: "array",
              items: { type: "string" },
              description: "Bullet point texts.",
            },
            chart_code: {
              type: "string",
              description:
                "Optional Python code (matplotlib) to generate a chart for this slide.",
            },
          },
          required: ["title", "bullets"],
        },
      },
    },
    required: ["title", "slides"],
  },
  async execute(args: Record<string, unknown>, ctx: AgentContext) {
    const title = String(args.title);
    const slides = args.slides as Array<{
      title: string;
      bullets: string[];
      chart_code?: string;
    }>;

    try {
      const PptxGenJS = (await import("pptxgenjs")).default;
      const pres = new PptxGenJS();

      const BG = "0A0A0F";
      const TEXT = "E8E8EC";
      const ACCENT = "A78BFA";

      pres.layout = "LAYOUT_WIDE";

      // --- Title slide ---
      const titleSlide = pres.addSlide();
      titleSlide.background = { color: BG };
      titleSlide.addText(title, {
        x: 0.8,
        y: 2.0,
        w: "80%",
        fontSize: 36,
        bold: true,
        color: TEXT,
        fontFace: "Arial",
      });
      titleSlide.addText("Generated by Hyprnova Board", {
        x: 0.8,
        y: 3.4,
        w: "80%",
        fontSize: 14,
        color: ACCENT,
        fontFace: "Arial",
      });

      // --- Content slides ---
      for (const s of slides) {
        const slide = pres.addSlide();
        slide.background = { color: BG };

        // Heading
        slide.addText(s.title, {
          x: 0.6,
          y: 0.3,
          w: "90%",
          fontSize: 24,
          bold: true,
          color: TEXT,
          fontFace: "Arial",
        });

        // Accent underline
        slide.addShape(pres.ShapeType.rect, {
          x: 0.6,
          y: 0.85,
          w: 1.2,
          h: 0.04,
          fill: { color: ACCENT },
        });

        const hasChart = !!s.chart_code;
        const bulletW = hasChart ? "45%" : "85%";

        // Bullets
        const bulletRows = s.bullets.map((b) => ({
          text: b,
          options: {
            fontSize: 14,
            color: TEXT,
            fontFace: "Arial",
            bullet: { code: "2022", color: ACCENT } as any,
            paraSpaceAfter: 8,
          },
        }));

        slide.addText(bulletRows as any, {
          x: 0.6,
          y: 1.1,
          w: bulletW,
          h: 4.0,
          valign: "top",
        });

        // Chart image (right half)
        if (s.chart_code) {
          const chartBuf = await runChartInSandbox(s.chart_code);
          if (chartBuf) {
            slide.addImage({
              data: `image/png;base64,${chartBuf.toString("base64")}`,
              x: 6.8,
              y: 1.1,
              w: 5.5,
              h: 4.0,
            });
          }
        }
      }

      // Generate buffer
      const pptxData = (await pres.write({ outputType: "nodebuffer" })) as Buffer;
      const buffer = Buffer.from(pptxData);

      const sanitizedTitle = title
        .replace(/[^a-zA-Z0-9_-]/g, "_")
        .slice(0, 100);
      const fileName = `${sanitizedTitle}.pptx`;
      const storagePath = `outputs/${ctx.job.id}/${fileName}`;

      uploadFile(storagePath, buffer);

      const outputFile: OutputFile = {
        fileName,
        storagePath,
        fileSize: buffer.length,
        resultType: "pptx",
      };

      return {
        success: true,
        data: {
          file_name: fileName,
          format: "pptx",
          size_bytes: buffer.length,
          storage_path: storagePath,
          download_url: `/api/files/download?id=${storagePath}`,
          slide_count: slides.length + 1,
        },
        output_files: [outputFile],
      };
    } catch (err) {
      return {
        success: false,
        data: {
          error:
            err instanceof Error
              ? err.message
              : "Failed to generate slides",
        },
      };
    }
  },
};
